### PR TITLE
Add configuration man pages to some plugins

### PR DESCRIPTION
**Pull request by buschmann23**
I wrote small man pages for some of my plugins describing the various configuration file options read by this plugins. In particular they cover the following plugins:
* Memcached
* MemcachedSessionStore
* CSRFProtection
They will be installed in the man page section number 5 (File formats and configuration files).

### CODE REVIEW

**Comment by buschmann23** [comment]
I now also added a man page for the Session plugin, because it also has config file options.

**Comment by dantti** [comment]
Sorry but why man pages to plugins?
For the binaries I find important but isn't doxygen enough?

**Comment by buschmann23** [comment]
Only for the configuration of the plugins - not the API part. I often find it useful when working on remote servers to have information in man pages without the need to search for the documentation in the web. And on rpm based distributions I can simply use `rpm -q -d package` to show documentation files for packages. (I think there will be similar stuff for debs) Also I can refer from one man page to another.

For sure, everything is still available in the web, especially in the API docs. But as a pure user I would find it hard to find e.g. the settings for the Session plugin in the description of the setup method. :)

**Comment by dantti** [comment]
Could you please add some skell for man pages of cutelyst and cutelyst-wsig binaries, I didn't wrote any yet due not having a template on any project... I can write the content no problem

**Comment by buschmann23** [comment]
Yes, will create some.

**Pull request merged**
