### PR TITLE
Improve building of API documentation

### PR DESCRIPTION
**Pull request by buschmann23**
This improves the building of the API documentation, especially if modularized Qt doc files are available. It is still possible to use one big tag file for Qt. It only links to HTML and QCH documentation if the files/directories to link to can be found.

Beside the option to specify one single big tag file, it now allows to set a directory, that contains the Qt documentation and the corresponding tag files. The default value for this directory is the return value of `qmake -query QT_INSTALL_DOCS`.

It now also creates three types of ducumentation:

Online usable HTML docs linked to the online docs of Qt and libstdc++ (if
the tag files are available), saved into `${CMAKE_BINARY_DIR}/webdox`.

Local usable HTML docs linked to local available HTML docs of Qt and
libstdc++ (if the tag files are available), saved into
`${CMAKE_BINARY_DIR}/htmldox`.

Local usable QCH file linked to local available QCH files of Qt and
libstdc++ (if the tag files are available), saved into `${CMAKE_BINARY_DIR}/qtdocs`
and `${CMAKE_BINARY_DIR}/cutelyst${PROJECT_VERSION_MAJOR}.qch`.

Building the docs also gained two more options, beside `BUILD_DOCS`:

`BUILD_DOCS_QUIET` suppresses most of the doxygen output while running. Output is enabled by default, but this makes it easier to disable output for automated builds in systems like open build service where it increases the build logs.

`BUILD_DOCS_TIMESTAMP` manages if the generated HTML files should include timestamps. This is also useful for package builds where every automated rebuild would be treated as changed only because of different time stamps in the files.

Furthermore I added a small fix for recognizing doxygen. It seems that `DOXYGEN_DOT_FOUND` is not set correctly if it is required as package component, at least not on cmake 3.10 and 3.16. CMake 3.9 introduced an improved FindDoxygen module, so lets set this manually for CMake 3.9 or newer.

I also renamed the variables used to configure the Doxyfiles according to the naming schema introduced for `doxygen_add_docs()`, see also https://cmake.org/cmake/help/v3.9/module/FindDoxygen.html

### CODE REVIEW

**Comment by dantti** [comment]
looks fine, I added BUILD_DOCS because find doxygen was simple freezing.. also I don't need need to make docs all the time..

**Comment by dantti** [comment]
tho on Travis it's failing due dot

**Comment by buschmann23** [comment]
> looks fine, I added BUILD_DOCS because find doxygen was simple freezing.. also I don't need need to make docs all the time..

Maybe because of this: https://gitlab.kitware.com/cmake/cmake/-/issues/

I use a patch for this in my OBS instance for affected versions.

**Comment by buschmann23** [comment]
> tho on Travis it's failing due dot

Ah, I think this is now because of
`option(BUILD_DOCS "Add the make docs target to build the documentationn. Requires doxygen and dot" ${BUILD_ALL})`

Before it was disabled by default, now it is enabled when BUILD_ALL is enabled. So we could either adopt travis config or I set it to `OFF` instead of `${BUILD_ALL}`.

**Pull request merged**
