### PR TITLE
Fix CMake error. Wrong syntax.

### PR DESCRIPTION
**Pull request by MohdFahmiNoorain**

### CODE REVIEW

**Comment by dantti** [comment]
Oh, and BTW Travis CI uses Ubuntu 14.04 LTS with CMake 2.8.12 and doesn't show any warning/error do you know why?

**Comment by MohdFahmiNoorain** [comment]
I truly no idea why....

**Comment by dantti** [comment]
This was a CMake bug fixed by https://github.com/Kitware/CMake/commit/dede273193139793d18e3e3fe800acec27140f06
as a workaround you could try to using only PRIVATE, PRIVATE... (without the link part) as it seems from the commit which that is fine.

**Comment by dantti** [comment]
I'm closing this since it's an old cmake bug and I have changed most links to just PRIVATE without alternating so the issue should work even with buggy cmake.

**Pull request closed without merging**
