### PR TITLE
Documentation improvements

### PR DESCRIPTION
**Pull request by buschmann23**
* adds Memcached and CSRF protection to the plugin list in the README.md
* adds CSRFProtection to the plugin list on the API docs main page
* adds a note about limitations to the MemcachedSessionStore plugin API docs

### CODE REVIEW

**Comment by dantti** [comment]
did you see the broken build?

**Comment by buschmann23** [comment]
Yes. And that is interesting. I did not change the source, only documentation. The `const std::__cxx11::string &config` has been there all the time. I ever thought you added it. But maybe it was accidentally added by Qt Creator's auto completion feature. I have the same error when building packages for older releases of openSUSE and there I am patching it away.

**Comment by buschmann23** [comment]
For the error with the too much arguments for the libmemcached function, that seems to be because of an too old version of libmemcached. Will add a version check to the pkg_search_module cmake call.

**Comment by dantti** [comment]
actually that was broken before this PR, I didn't see it before. If a version check can fix the build great, too bad it won't be tested by travis then

**Comment by buschmann23** [comment]
As this is deprecated anyway, I only added a version check to require libmemcached >= 1.0.10

**Pull request merged**
