### PR TITLE
Use versioned directories for plugins

### PR DESCRIPTION
**Pull request by buschmann23**
This changes will install the cutelyst plugins/actions (RenderView, REST and RoleACL) into a versioned directory by default (e.g. /usr/lib64/cutelyst/2.10).

The cutelyst grantlee plugins will be installed by default into the versioned default directory used by grantlee instead of the cutelyst plugins dir (e.g. /usr/lib64/grantlee/5.1).

The environment variable to specify additional grantlee plugin paths has been renamed from CUTELYST_PLUGINS_DIR to GRANTLEE_PLUGINS_DIR to clarify what kind of plugin is meant.

### CODE REVIEW

**Comment by dantti** [comment]
it should be versioned to 2 today no? what advantages to have a minor version on tem dir name? I only see disavantages

**Comment by buschmann23** [comment]
I oriented on how grantlee is doing the version stuff for its plugins. When I have a look into /usr/lib64 on my distro (openSUSE), some stuff there uses full version, some no version, some sonum inside there plugin directories.

In GNU autotools there is pkglibdir for this purpose that we already have - but without version or sonum. IMHO we should at least use the sonum or the major version there to not have conflicts when increasing this values.

So we could use
`set (PKGLIBDIR "${LIBDIR}/cutelyst${CUTELYST_API_LEVEL}")`

And then remove `CUTELYST_PLUGINS_DIR` and use `PKGLIBDIR`.

**Comment by Conan-Kudo** [comment]
I don't see any particular advantages with versioning to the minor version, considering Cutelyst generally offers ABI compatibility at the major version.

**Comment by dantti** [comment]
Today I hit an issue were the versioned scheme of Grantlee just made it harder to find out why Grantlee v5.2.0 didn't load Cutelyst plugins.. I also pushed some changes to fix Cutelyst finding it's own plugins on Debian based, it seems Fedora/Suse use CMAKE_INSTALL_LIBDIR with absolute path which wasn't the case on Ubuntu/Debian...

**Comment by Conan-Kudo** [comment]
@dantti That's not true. Fedora only sets `CMAKE_INSTALL_PREFIX` to `/usr`. There's a bug in the SUSE cmake macros that needs to be fixed to stop setting `CMAKE_INSTALL_LIBDIR`, since it's not necessary.

**Comment by dantti** [comment]
@Conan-Kudo well I could only make the code have the proper path prepending the install prefix.

**Comment by buschmann23** [comment]
@dantti Yes, the issue with the versioned plugin directory of Grantlee after upgrading to version 5.2 was the reason for me, to think about this for Cutelyst. Having an unversioned directory would make it easier to upgrade but would make it harder to have two versions of Cutelyst to be installed. We could leave it as unversioned but configurable, so that the distro packagers could decide if they want to have it versioned or not.

Ah, I now saw that you already made this change. :)

**Comment by dantti** [comment]
can I close this then?

**Comment by buschmann23** [comment]
If you want to keep the current installation path for the Grantlee plugins, close it. IMHO we should install our Grantlee plugins into the default Grantlee plugin path instead of the Cutelyst plugin path as this is what `grantlee_adjust_plugin_name` internally does when applied to a plugin. But I can also create a new PR for that if wanted. :)

**Comment by dantti** [comment]
Ok, we can install on their plugin path, a new PR is best indeed, now that Grantlee is at KDE we need to make it inject without relying on this plugin mechanism.

**Pull request closed without merging**
