### PR TITLE
Chdir to project root on Windows after the app dll load

### PR DESCRIPTION
**Pull request by texpert**
Do not set chdir after project find - on Windows, for example, this
causes a chdir out of the directory containing dlls, resulting in a `dll
could not be found error`.

### CODE REVIEW

**Comment by dantti** [comment]
Please use branches when submiting PR, and do a rebase master to not have merge commits, this way I can review individual PR, this one is including commits from the other which I'm waiting to hear your comments on the questions I raised.

**Comment by dantti** [comment]
About this last do no chdir, I don't understand the issue very well, can you give an example, this will also break on Unix, so if it's the case it must have #ifndef Q_OS_WIN

**Comment by texpert** [comment]
On Windows this chdir is going to project root. thus losing the dll to load:
```
C:\Hello\build\src\Debug>cutelyst -r --server --app-file Hello.dll
Cutelyst-WSGI starting
Cutelyst-WSGI starting
WSGI socket 0 bound to TCP address 0.0.0.0:3000 fd 624
Changing directory to: C:/Hello
Loading application: Hello.dll
2100:5984 wsgi[critical] Could not load application: "The shared library was not found."
5632:5640 wsgi.win[debug] Master child finished 1 QProcess::ExitStatus(NormalExit)
Cutelyst-WSGI terminated
```

I will follow your advise to make it OS-aware.

**Comment by dantti** [comment]
This chdir is needed to get to the root of the project because there it will usually finds templates in root/src, does using chdir2 works for you? I guess that it might be better in this case then.

**Comment by texpert** [comment]
Yep, @dantti , chdir2 did the trick, thanks!

**Comment by dantti** [comment]
ok, now I'll check if chdir2 works on unix too, so that the ifdef is not needed, but you also need to use branches for PR, as I can't merge this which includes all your other changes.
For each PR you do create a new branch off master, and always use git rebase master to not get merge commits.

**Comment by dantti** [comment]
I did the test here, and an extra change on wsgi would be needed so I did the commit, thanks for spotting the issue :)

**Pull request closed without merging**
