### PR TITLE
Supress MSVC warnings for Cutelyst and generated apps

### PR DESCRIPTION
**Pull request by texpert**

### CODE REVIEW

**Comment by dantti** [comment]
What warnings are these that need to be suppressed? Can't we fix the warning instead of suppressing them?

**Comment by texpert** [comment]
The majority of the warnings belong  to MS:
```
"C:\cutelyst\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\cutelyst\build\tests\testvalidator_exec.vcxproj" (default target) (49) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\xutility(3326): warning C4996: 'std::is_permutation::_Unchecked_iterators::_Deprecate': Call to 'std::is_permutation' with parameters that may be unsafe - this call relies on the caller to check that the passed values are correct. To disable this warning, use -D_SCL_SECURE_NO_WARNINGS. See documentation on how to use Visual C++ 'Checked Iterators' [C:\cutelyst\build\tests\testvalidator_exec.vcxproj]
```
and also to Qt:

```
  C:\Qt\5.9.1\msvc2017_64\include\QtCore/qhash.h(953): note: see reference to function template instantiation 'bool std::is_permutation<QHash<QString,QString>::const_iterator,T1>(_FwdIt1,_FwdIt1,_FwdIt2)' being compiled
          with
          [
              T1=QHash<QString,QString>::const_iterator,
              _FwdIt1=QHash<QString,QString>::const_iterator,
              _FwdIt2=QHash<QString,QString>::const_iterator
          ]
  C:\Qt\5.9.1\msvc2017_64\include\QtCore/qhash.h(932): note: while compiling class template member function 'bool QHash<QString,QString>::operator ==(const QHash<QString,QString> &) const'
```

There are few in Cutelyst, though:

```
  c:\cutelyst\cutelyst\headers.h(371): note: see reference to function template instantiation 'bool QHash<QString,QString>::operator ==(const QHash<QString,QString> &) const' being compiled
  c:\cutelyst\cutelyst\headers.h(389): note: see reference to class template instantiation 'QHash<QString,QString>' being compiled
```

**Comment by texpert** [comment]
I found the cause of warnings - QHash is using internally the old unsafe std::is_permutation - http://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/tools/qhash.h?h=v5.9.1#n953, which is deprecated - http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0174r0#4.13

So, @dantti , I think that it is reasonable to supress these warnings.

**Comment by dantti** [comment]
I'm not entirely sure this is fine, but I cherry-picked it from your fork, oh and BTW you forgot the qtcreator plugin, I still need to use qtcreator's plugin files in cutelyst cmd to avoid duplication, but there are more important stuff to be done atm...
Thanks.

**Comment by texpert** [comment]
OK, @dantti ! Sorry, I have no time right now for more testing, but I'll be back :)

**Pull request closed without merging**
